### ISSUE TITLE
`max` by itself doesn't work to find the longest word in a list

### ISSUE THREAD

**Issue by lindseyberlin** [learn-co-curriculum/dsc-python-operators-functions-and-methods-lab#3]
`max(longest_word_in_list)` does not return the longest element in the list, as shown in the solution, without designating a key: `max(longest_word_in_list, key=len)`
(what it's doing now is choosing the element that starts with the highest ASCII value)

**Comment by bpurdy-ds** [comment]
Fixed.

**Comment by bpurdy-ds** [comment]
And it's fine for v3.0 Phase 0.
